const CONFIG = {


  //getCourseDataByLocation
  // Your Google Drive Folder ID for PDFs
  ADMISSIONS_PDF_FOLDER_ID: '1z9SkGw0JXQmlj_NjLcK7Cal1Vvgctcwr',

  // Using active spreadsheet for all operations - no separate IDs needed

  // Sheet Names
  ADMISSIONS_SHEET_NAME: 'ADMISSIONF',
  ENROLLMENTS_SHEET_NAME: 'Enrollments',
  INQUIRY_SHEET_NAME: 'Inquiries', // Your main inquiry sheet
  STUDENT_DATA_SHEET_NAME: 'STUDENT DATA',
  FEES_SHEET_NAME: 'FEES',
  LOGIN_SHEET_NAME: 'LOGIN',
  DROPDOWN_SHEET_NAME: 'DROPDOWN',
  AUDIT_LOG_SHEET_NAME: 'AuditLog',
  RECEIPTS_SHEET_NAME: 'Receipts',
  INSTALLMENT_PAYMENTS_SHEET_NAME: 'InstallmentPayments',

  EXAMRECEIPT_SHEET_NAME: 'RECEIPT',

  DEFAULT_USER: 'Anonymous',
  ROLES: {
    ADMIN: 'admin'
  },

  // --- Column Mappings for INQUIRY_SHEET_NAME ('Inquiries') ---
  // These indices (0-based) must match the column order in your 'Inquiries' Google Sheet precisely,
  // assuming Column A is an auto-generated timestamp.
  //
  // Your sheet columns are effectively:
  // Col A: [Timestamp (Auto-generated by appendRow)]
  // Col B: Date (from form)
  // Col C: Aadhar
  // Col D: Full Name
  // Col E: Qualification
  // Col F: Phone Number
  // Col G: WhatsApp Number
  // Col H: Parents Number
  // Col I: Email Address
  // Col J: Age
  // Col K: Address
  // Col L: Interested Course
  // Col M: Inquiry Taken By
  // Col N: Branch
  // Col O: Follow-up Date
  // Col P: Notes
  // Col Q: Admission Status
  // Col R: Admission Date
  // Col S: Batch Assigned
  // Col T: Logged In User ID (if appended after form data)

  INQUIRY_COLUMN_INDEX: {
    // These indices are 0-based relative to the *data array that will be appended*,
    // where the Timestamp (Col A) is automatically added by Google Sheets and isn't
    // part of the data you explicitly pass in `appendRow([Timestamp, ...rowData])`.
    // So, if your `rowData` starts with 'Date (from form)' which goes into Col B,
    // its index in `rowData` is 0.
    // However, for lookup (getValues()), the Timestamp *is* included, so indices will shift.

    DATE_FORM: 0,           // Corresponds to Col B in sheet
    AADHAAR: 1,             // Corresponds to Col C in sheet
    FULL_NAME: 2,           // Corresponds to Col D in sheet
    QUALIFICATION: 3,       // Corresponds to Col E in sheet
    PHONE_NUMBER: 4,        // Corresponds to Col F in sheet
    WHATSAPP_NUMBER: 5,     // Corresponds to Col G in sheet
    PARENTS_NUMBER: 6,      // Corresponds to Col H in sheet
    EMAIL_ADDRESS: 7,       // Corresponds to Col I in sheet
    AGE: 8,                 // Corresponds to Col J in sheet
    ADDRESS: 9,             // Corresponds to Col K in sheet
    INTERESTED_COURSE: 10,  // Corresponds to Col L in sheet
    INQUIRY_TAKEN_BY: 11,   // Corresponds to Col M in sheet
    BRANCH: 12,             // Corresponds to Col N in sheet
    FOLLOW_UP_DATE: 13,     // Corresponds to Col O in sheet
    NOTES: 14,              // Corresponds to Col P in sheet
    ADMISSION_STATUS: 15,   // Corresponds to Col Q in sheet
    ADMISSION_DATE: 16,     // Corresponds to Col R in sheet
    BATCH_ASSIGNED: 17,     // Corresponds to Col S in sheet
    LOGGED_IN_USER_ID: 18,   // Corresponds to Col T in sheet
    GENDER: 19
  },

  // --- Column Mappings for Aadhar Lookup (within INQUIRY_SHEET_NAME 'Inquiries') ---
  // These indices (0-based) must match the column order in your 'Inquiries' Google Sheet precisely,
  // when you use `getDataRange().getValues()`. This method includes ALL columns,
  // including the auto-generated Timestamp in Column A.
  //
  // Col A: Timestamp (index 0 in getValues() array)
  // Col B: Date (index 1)
  // Col C: Aadhar (index 2)
  // ...and so on.
  //
  // Therefore, these indices will be one higher than their corresponding visual column
  // if column A is Timestamp.

  AADHAAR_LOOKUP: {
    SHEET_NAME: 'Inquiries', // The sheet where Aadhar records are stored for lookup
    // These indices are 0-based from the `getValues()` array
    TIMESTAMP_COL: 0,            // Column A
    DATE_FORM_COL: 1,            // Column B
    AADHAAR_COL: 2,              // Column C
    FULL_NAME_COL: 3,            // Column D
    QUALIFICATION_COL: 4,        // Column E
    PHONE_NUMBER_COL: 5,         // Column F
    WHATSAPP_NUMBER_COL: 6,      // Column G
    PARENTS_NUMBER_COL: 7,       // Column H
    EMAIL_ADDRESS_COL: 8,        // Column I
    AGE_COL: 9,                  // Column J
    ADDRESS_COL: 10,             // Column K
    INTERESTED_COURSE_COL: 11,   // Column L
    INQUIRY_TAKEN_BY_COL: 12,    // Column M
    BRANCH_COL: 13,              // Column N
    FOLLOW_UP_DATE_COL: 14,      // Column O
    NOTES_COL: 15,               // Column P
    ADMISSION_STATUS_COL: 16,    // Column Q
    ADMISSION_DATE_COL: 17,      // Column R
    BATCH_ASSIGNED_COL: 18,      // Column S
    LOGGED_IN_USER_ID_COL: 19,   // Column T
    GENDER_COL: 20               // Column U
  },

  // --- Column Mappings for INSTALLMENT_PAYMENTS_SHEET_NAME ('InstallmentPayments') ---
  // These indices (0-based) must match the column order in your 'InstallmentPayments' Google Sheet precisely,
  // assuming Column A is an auto-generated timestamp.
  //
  // Your sheet columns are effectively:
  // Col A: Timestamp (Auto-generated by appendRow)
  // Col B: Enrollment_ID
  // Col C: Student_Name
  // Col D: Course_Name
  // Col E: Payement_Option
  // Col F: Total_Fees_Due
  // Col G: Installment_Number
  // Col H: Amount_Paid
  // Col I: Payment_Method
  // Col J: Payment_Date
  // Col K: Logged_In_User

  INSTALLMENT_PAYMENTS_COLUMN_INDEX: {
    // These indices are 0-based relative to the *data array that will be appended*,
    // where the Timestamp (Col A) is automatically added by Google Sheets and isn't
    // part of the data you explicitly pass in `appendRow([Timestamp, ...rowData])`.
    // So, if your `rowData` starts with 'Enrollment_ID' which goes into Col B,
    // its index in `rowData` is 0.
    // However, for lookup (getValues()), the Timestamp *is* included, so indices will shift.

    ENROLLMENT_ID: 0,           // Corresponds to Col B in sheet
    STUDENT_NAME: 1,            // Corresponds to Col C in sheet
    COURSE_NAME: 2,             // Corresponds to Col D in sheet
    PAYMENT_OPTION: 3,          // Corresponds to Col E in sheet
    TOTAL_FEES_DUE: 4,          // Corresponds to Col F in sheet
    INSTALLMENT_NUMBER: 5,      // Corresponds to Col G in sheet
    AMOUNT_PAID: 6,             // Corresponds to Col H in sheet
    PAYMENT_METHOD: 7,          // Corresponds to Col I in sheet
    PAYMENT_DATE: 8,            // Corresponds to Col J in sheet
    LOGGED_IN_USER: 9           // Corresponds to Col K in sheet
  },

  // --- Column Mappings for InstallmentPayments Lookup ---
  // These indices (0-based) must match the column order in your 'InstallmentPayments' Google Sheet precisely,
  // when you use `getDataRange().getValues()`. This method includes ALL columns,
  // including the auto-generated Timestamp in Column A.
  //
  // Col A: Timestamp (index 0 in getValues() array)
  // Col B: Enrollment_ID (index 1)
  // Col C: Student_Name (index 2)
  // ...and so on.

  INSTALLMENT_PAYMENTS_LOOKUP: {
    SHEET_NAME: 'InstallmentPayments', // The sheet where InstallmentPayments records are stored for lookup
    // These indices are 0-based from the `getValues()` array
    TIMESTAMP_COL: 0,            // Column A
    ENROLLMENT_ID_COL: 1,        // Column B
    STUDENT_NAME_COL: 2,         // Column C
    COURSE_NAME_COL: 3,          // Column D
    PAYMENT_OPTION_COL: 4,       // Column E
    TOTAL_FEES_DUE_COL: 5,       // Column F
    INSTALLMENT_NUMBER_COL: 6,   // Column G
    AMOUNT_PAID_COL: 7,          // Column H
    PAYMENT_METHOD_COL: 8,       // Column I
    PAYMENT_DATE_COL: 9,         // Column J
    LOGGED_IN_USER_COL: 10       // Column K
  },

  // --- Column Mappings for EXAMRECEIPT_SHEET_NAME ('RECEIPT') ---
  // These indices (0-based) must match the column order in your 'RECEIPT' Google Sheet precisely,
  // assuming Column A is an auto-generated timestamp.
  //
  // Your sheet columns are effectively:
  // Col A: Timestamp (Auto-generated by appendRow)
  // Col B: Receipt Date
  // Col C: Receipt Number
  // Col D: Student Name
  // Col E: Course Name
  // Col F: Total Amount
  // Col G: Payment Mode
  // Col H: Agree Terms

  EXAMRECEIPT_COLUMN_INDEX: {
    // These indices are 0-based relative to the *data array that will be appended*,
    // where the Timestamp (Col A) is automatically added by Google Sheets and isn't
    // part of the data you explicitly pass in `appendRow([Timestamp, ...rowData])`.
    // So, if your `rowData` starts with 'Receipt Date' which goes into Col B,
    // its index in `rowData` is 0.
    // However, for lookup (getValues()), the Timestamp *is* included, so indices will shift.

    RECEIPT_DATE: 0,           // Corresponds to Col B in sheet
    RECEIPT_NUMBER: 1,         // Corresponds to Col C in sheet
    STUDENT_NAME: 2,           // Corresponds to Col D in sheet
    COURSE_NAME: 3,            // Corresponds to Col E in sheet
    TOTAL_AMOUNT: 4,           // Corresponds to Col F in sheet
    PAYMENT_MODE: 5,           // Corresponds to Col G in sheet
    AGREE_TERMS: 6             // Corresponds to Col H in sheet
  },

  // --- Column Mappings for Exam Receipt Lookup ---
  // These indices (0-based) must match the column order in your 'RECEIPT' Google Sheet precisely,
  // when you use `getDataRange().getValues()`. This method includes ALL columns,
  // including the auto-generated Timestamp in Column A.
  //
  // Col A: Timestamp (index 0 in getValues() array)
  // Col B: Receipt Date (index 1)
  // Col C: Receipt Number (index 2)
  // Col D: Student Name (index 3)
  // Col E: Course Name (index 4)
  // Col F: Total Amount (index 5)
  // Col G: Payment Mode (index 6)
  // Col H: Agree Terms (index 7)

  EXAMRECEIPT_LOOKUP: {
    SHEET_NAME: 'RECEIPT', // The sheet where Exam Receipt records are stored for lookup
    // These indices are 0-based from the `getValues()` array
    RECEIPT_DATE_COL: 0,         // Column A
    RECEIPT_NUMBER_COL: 1,       // Column B
    STUDENT_NAME_COL: 2,         // Column C
    COURSE_NAME_COL: 3,         // Column D
    TOTAL_AMOUNT_COL: 4,         // Column E
    PAYMENT_MODE_COL: 5,         // Column F
    AGREE_TERMS_COL: 6,          // Column G
    RECORD_TIMESTAMP_COL: 7,     // Column H
    USER_ID_COL: 8               // Column I
  },

  // --- Column Mappings for Fee Structure Table ---
  // These indices (0-based) must match the column order in your fee structure table precisely.
  // The fee structure table contains the following attributes:
  // TimeStamp, Enrollment ID, Name, Course_Name, Payment Mode, Admission_Fee, Admission_Fee_Due,
  // Course_Fee, Exam_Fee, Exam_Fee_Due, Total_Amount_Due, Branch, User_Name

  FEE_STRUCTURE_SHEET_NAME: 'FeeStructure',

  FEE_STRUCTURE_COLUMN_INDEX: {
    // These indices are 0-based relative to the *data array that will be appended*,
    // where the Timestamp (Col A) is automatically added by Google Sheets and isn't
    // part of the data you explicitly pass in `appendRow([Timestamp, ...rowData])`.
    // So, if your `rowData` starts with 'Enrollment ID' which goes into Col B,
    // its index in `rowData` is 0.

    ENROLLMENT_ID: 0,        // Corresponds to Col B in sheet (Enrollment ID)
    NAME: 1,                 // Corresponds to Col C in sheet (Name)
    COURSE_NAME: 2,          // Corresponds to Col D in sheet (Course_Name)
    PAYMENT_MODE: 3,         // Corresponds to Col E in sheet (Payment Mode)
    ADMISSION_FEE: 4,        // Corresponds to Col F in sheet (Admission_Fee)
    ADMISSION_FEE_DUE: 5,    // Corresponds to Col G in sheet (Admission_Fee_Due)
    COURSE_FEE: 6,           // Corresponds to Col H in sheet (Course_Fee)
    COURSE_FEE_DUE: 7,       // Corresponds to Col I in sheet (Course_Fee_Due) - NEW
    EXAM_FEE: 8,             // Corresponds to Col J in sheet (Exam_Fee)
    EXAM_FEE_DUE: 9,         // Corresponds to Col K in sheet (Exam_Fee_Due)
    TOTAL_AMOUNT_DUE: 10,    // Corresponds to Col L in sheet (Total_Amount_Due)
    BRANCH: 11,              // Corresponds to Col M in sheet (Branch)
    USER_NAME: 12            // Corresponds to Col N in sheet (User_Name)
  },

  // --- Column Mappings for Fee Structure Lookup ---
  // These indices (0-based) must match the column order in your fee structure table precisely,
  // when you use `getDataRange().getValues()`. This method includes ALL columns,
  // including the auto-generated Timestamp in Column A.

  FEE_STRUCTURE_LOOKUP: {
    SHEET_NAME: 'FeeStructure',
    // These indices are 0-based from the `getValues()` array
    TIMESTAMP_COL: 0,             // Column A (TimeStamp)
    ENROLLMENT_ID_COL: 1,         // Column B (Enrollment ID)
    NAME_COL: 2,                  // Column C (Name)
    COURSE_NAME_COL: 3,           // Column D (Course_Name)
    PAYMENT_MODE_COL: 4,          // Column E (Payment Mode)
    ADMISSION_FEE_COL: 5,         // Column F (Admission_Fee)
    ADMISSION_FEE_DUE_COL: 6,     // Column G (Admission_Fee_Due)
    COURSE_FEE_COL: 7,            // Column H (Course_Fee)
    COURSE_FEE_DUE_COL: 8,        // Column I (Course_Fee_Due) - NEW
    EXAM_FEE_COL: 9,              // Column J (Exam_Fee)
    EXAM_FEE_DUE_COL: 10,         // Column K (Exam_Fee_Due)
    TOTAL_AMOUNT_DUE_COL: 11,     // Column L (Total_Amount_Due)
    BRANCH_COL: 12,               // Column M (Branch)
    USER_NAME_COL: 13             // Column N (User_Name)
  }
};


